export function money(value) {
  return `${Number(value || 0).toLocaleString('vi-VN')} đ`;
}

export function dateTime(value) {
  if (!value) return '';
  return new Date(value).toLocaleString('vi-VN');
}

export function shortDate(value) {
  if (!value) return '';
  return new Date(value).toLocaleDateString('vi-VN');
}

export function classNames(...parts) {
  return parts.filter(Boolean).join(' ');
}

export function statusClass(status) {
  return `status-pill status-${String(status || '').replace(/\s+/g, '_')}`;
}

export function isImageUrl(value) {
  return typeof value === 'string'
    && /^(https?:\/\/|\/)/.test(value)
    && /\.(png|jpe?g|webp|gif|avif)(\?|$)/i.test(value);
}

export function fieldLabel(field) {
  const labels = {
    id: 'ID',
    role_id: 'Vai trò',
    role_name: 'Vai trò',
    username: 'Tài khoản',
    password: 'Mật khẩu',
    password_hash: 'Mã mật khẩu',
    is_active: 'Đang bật',
    user_id: 'Người dùng',
    full_name: 'Họ tên',
    email: 'Email',
    phone: 'Số điện thoại',
    address: 'Địa chỉ',
    loyalty_points: 'Điểm',
    membership_rank: 'Hạng',
    rank_name: 'Hạng',
    min_points: 'Điểm tối thiểu',
    discount_percent: 'Giảm giá %',
    point_multiplier: 'Nhân điểm',
    birthday_reward_amount: 'Quà sinh nhật',
    free_shipping_min_order: 'Freeship từ',
    benefits: 'Quyền lợi',
    name: 'Tên',
    description: 'Mô tả',
    contact_name: 'Người liên hệ',
    tax_code: 'Mã số thuế',
    bank_name: 'Ngân hàng',
    bank_account: 'Số tài khoản',
    payment_terms: 'Điều khoản thanh toán',
    lead_time_days: 'Ngày giao dự kiến',
    category_id: 'Danh mục',
    category_name: 'Danh mục',
    short_description: 'Mô tả ngắn',
    price: 'Giá',
    base_cost: 'Giá vốn',
    barcode: 'Barcode',
    sku: 'SKU',
    stock_quantity: 'Tồn kho',
    min_stock_level: 'Tối thiểu',
    recipe_required: 'Cần công thức',
    recipe_status: 'Trạng thái công thức',
    preparation_minutes: 'Phút pha chế',
    view_count: 'Lượt xem',
    sales_count: 'Đã bán',
    is_best_seller: 'Bán chạy',
    image_url: 'Nguồn ảnh',
    product_id: 'Sản phẩm',
    product_name: 'Sản phẩm',
    is_primary: 'Ảnh chính',
    display_order: 'Thứ tự',
    variant_id: 'Biến thể',
    variant_name: 'Biến thể',
    price_adjustment: 'Chênh giá',
    recipe_multiplier: 'Hệ số công thức',
    cup_volume_ml: 'Dung tích ml',
    supplier_id: 'Nhà cung cấp',
    supplier_name: 'Nhà cung cấp',
    material_code: 'Mã nguyên liệu',
    material_type: 'Loại nguyên liệu',
    unit: 'Đơn vị',
    recipe_unit: 'Đơn vị công thức',
    conversion_rate: 'Tỷ lệ quy đổi',
    last_import_price: 'Giá nhập cuối',
    average_cost: 'Giá vốn TB',
    stock_value: 'Giá trị kho',
    reorder_point: 'Mốc đặt thêm',
    shelf_life_days: 'Hạn dùng ngày',
    storage_note: 'Ghi chú bảo quản',
    material_id: 'Nguyên liệu',
    material_name: 'Nguyên liệu',
    step_name: 'Công đoạn',
    step_order: 'Thứ tự công đoạn',
    quantity: 'Số lượng',
    loss_percent: 'Hao hụt %',
    is_optional: 'Tùy chọn',
    admin_id: 'Admin',
    total_amount: 'Tổng tiền',
    paid_amount: 'Số tiền đã ghi nhận',
    import_date: 'Ngày nhập',
    import_code: 'Mã phiếu nhập',
    expected_date: 'Ngày dự kiến',
    invoice_number: 'Số hóa đơn NCC',
    note: 'Ghi chú',
    import_id: 'Phiếu nhập',
    import_detail_id: 'Dòng nhập',
    batch_code: 'Mã lô',
    unit_price: 'Đơn giá',
    subtotal: 'Tạm tính',
    manufacturing_date: 'Ngày sản xuất',
    expiry_date: 'Hạn dùng',
    initial_quantity: 'SL ban đầu',
    remaining_quantity: 'SL còn lại',
    received_at: 'Nhận lúc',
    is_closed: 'Đã đóng lô',
    batch_id: 'Lô nguyên liệu',
    reference_type: 'Nguồn giao dịch',
    reference_id: 'Mã tham chiếu',
    quantity_change: 'Biến động kho',
    unit_cost: 'Giá vốn đơn vị',
    stock_after: 'Tồn sau GD',
    created_by: 'Người tạo',
    created_by_username: 'Người tạo',
    stat_date: 'Ngày thống kê',
    stat_year: 'Năm',
    stat_month: 'Tháng',
    stat_quarter: 'Quý',
    gross_revenue: 'Doanh thu gộp',
    net_revenue: 'Doanh thu thuần',
    completed_orders: 'Đơn hoàn tất',
    cancelled_orders: 'Đơn hủy',
    total_orders: 'Tổng đơn',
    items_sold: 'Sản phẩm bán',
    average_order_value: 'Giá trị đơn TB',
    invoice_count: 'Số hóa đơn',
    pending_count: 'Chờ xử lý',
    paid_count: 'Đã thanh toán',
    preparing_count: 'Đang chuẩn bị',
    completed_count: 'Hoàn tất',
    cancelled_count: 'Đã hủy',
    refunded_count: 'Hoàn tiền',
    cash_count: 'Tiền mặt',
    online_count: 'Online',
    cart_id: 'Giỏ hàng',
    topping_ids: 'Topping',
    option_hash: 'Mã tùy chọn',
    scope: 'Phạm vi',
    priority: 'Ưu tiên',
    original_price: 'Giá gốc',
    sale_price: 'Giá bán',
    discount_label: 'Nhãn giảm',
    discount_title: 'Chương trình giảm',
    discount_scope: 'Phạm vi giảm',
    code: 'Mã',
    title: 'Tiêu đề',
    discount_type: 'Loại giảm',
    discount_value: 'Giá trị giảm',
    minimum_order_amount: 'Đơn tối thiểu',
    required_membership_rank: 'Hạng yêu cầu',
    usage_limit: 'Giới hạn',
    used_count: 'Đã dùng',
    start_date: 'Ngày bắt đầu',
    end_date: 'Ngày kết thúc',
    membership_tier_id: 'Hạng hội viên',
    gift_type: 'Loại quà',
    gift_value: 'Giá trị quà',
    vehicle_type: 'Loại xe',
    license_plate: 'Biển số',
    promotion_id: 'Khuyến mãi',
    promotion_code: 'Mã KM',
    receiver_name: 'Người nhận',
    receiver_phone: 'SĐT nhận',
    delivery_address: 'Địa chỉ giao',
    discount_amount: 'Giảm giá',
    status: 'Trạng thái',
    order_id: 'Đơn hàng',
    ice_level: 'Đá',
    sugar_level: 'Đường',
    driver_id: 'Tài xế',
    driver_name: 'Tài xế',
    pickup_address: 'Điểm lấy',
    estimated_arrival: 'Dự kiến',
    delivered_at: 'Đã giao lúc',
    amount: 'Số tiền',
    method: 'Phương thức',
    transaction_code: 'Mã GD',
    paid_at: 'Thanh toán lúc',
    transaction_type: 'Loại điểm',
    points: 'Điểm',
    reason: 'Lý do',
    action: 'Hành động',
    entity_type: 'Bảng',
    entity_id: 'Mã dữ liệu',
    ip_address: 'IP',
    user_agent: 'Thiết bị',
    target_link: 'Liên kết',
    placement: 'Vị trí',
    starts_at: 'Bắt đầu',
    ends_at: 'Kết thúc',
    district: 'Quận/Huyện',
    city: 'Thành phố',
    opening_hours: 'Giờ mở cửa',
    map_url: 'Bản đồ',
    slug: 'Slug',
    excerpt: 'Tóm tắt',
    content: 'Nội dung',
    post_type: 'Loại bài',
    is_published: 'Đã đăng',
    published_at: 'Ngày đăng',
    session_id: 'Phiên chat',
    sender: 'Người gửi',
    message: 'Tin nhắn',
    created_at: 'Tạo lúc',
    updated_at: 'Cập nhật'
  };

  return labels[field] || field.replace(/_/g, ' ');
}

export function truncate(value, length = 80) {
  const text = String(value ?? '');
  return text.length > length ? `${text.slice(0, length)}...` : text;
}
